#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Register the auto loader as early as possible, so that we can use it in our own files.
require __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';

$kernel = $app->make(\Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(new \Symfony\Component\Console\Input\ArgvInput, new \Symfony\Component\Console\Output\ConsoleOutput));
