import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const LanguageContext = createContext(null)
const STORAGE_KEY = 'shemachoch_language'

export const languages = [
  { code: 'en', label: 'English', shortLabel: 'EN' },
  { code: 'am', label: 'አማርኛ', shortLabel: 'አማ' },
  { code: 'or', label: 'Afaan Oromo', shortLabel: 'OR' },
]

const dictionary = {
  en: {
    'common.language': 'Language',
    'common.portal': 'Portal',
    'common.close': 'Close',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.search': 'Search',
    'common.details': 'Details',
    'common.items': 'items',
    'common.product': 'Product',
    'common.general': 'General',
    'common.loading': 'Loading',
    'common.category': 'Category',
    'common.price': 'Price',
    'common.stock': 'Stock',
    'common.value': 'Value',
    'nav.dashboard': 'Dashboard',
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.orders': 'Orders',
    'nav.profile': 'Profile',
    'nav.messages': 'Messages',
    'nav.inventory': 'Inventory',
    'nav.suppliers': 'Suppliers',
    'nav.users': 'Users',
    'nav.reports': 'Reports',
    'nav.broadcasts': 'Broadcasts',
    'nav.supply': 'Supply',
    'nav.cart': 'Cart',
    'nav.logout': 'Logout',
    'nav.tagline': 'Professional Shemachoch commerce portal',
    'nav.subtagline': 'Orders, inventory, verification, and reports in one workspace',
    'auth.portalSubtitle': 'Professional ecommerce portal',
    'auth.memberCommerce': 'Member commerce',
    'auth.heroTitle': 'Shop, verify, and manage orders from one polished workspace.',
    'auth.heroCopy': 'A dense, operational experience for members, managers, and administrators.',
    'auth.liveInventory': 'Live inventory',
    'auth.secureCheckout': 'Secure checkout',
    'auth.adminReports': 'Admin reports',
    'auth.signIn': 'Sign in',
    'auth.accessWorkspace': 'Access your Shemachoch workspace.',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.signingIn': 'Signing in...',
    'auth.signInButton': 'Sign In',
    'auth.or': 'OR',
    'auth.google': 'Continue with Google',
    'auth.noAccount': 'Do not have an account?',
    'auth.createOne': 'Create one',
    'auth.createAccount': 'Create account',
    'auth.join': 'Join Shemachoch and start your verification.',
    'auth.fullName': 'Full Name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.passwordHint': 'Min 8 characters',
    'auth.confirmPasswordHint': 'Re-enter password',
    'auth.terms': 'I agree to the Terms of Service and Privacy Policy.',
    'auth.creating': 'Creating account...',
    'auth.alreadyAccount': 'Already have an account?',
    'auth.sideTitle': 'A professional shopping and operations portal for the whole store.',
    'auth.sideCopy': 'Create an account, submit verification, and access member pricing once approved.',
    'auth.loginFailed': 'Login failed',
    'products.marketEyebrow': 'Member marketplace',
    'products.title': 'Shop Shemachoch essentials',
    'products.description': 'Search live inventory, compare member prices, and build your pickup order from available stock.',
    'products.searchPlaceholder': 'Search products, categories, and descriptions',
    'products.allCategories': 'All Categories',
    'products.all': 'All',
    'products.noProducts': 'No products found',
    'products.noProductsDesc': 'Try changing your search term or selecting a different category.',
    'products.memberPrice': 'Member price',
    'products.available': 'available',
    'products.availableInStock': 'available in stock',
    'products.addToCart': 'Add to Cart',
    'products.added': 'Added',
    'products.verifyToBuy': 'Verify to buy',
    'products.unavailable': 'Unavailable',
    'products.qualityFallback': 'Quality Shemachoch product.',
    'products.verificationRequired': 'Verification required.',
    'products.outOfStock': 'This product is out of stock',
    'products.maxStock': 'Cannot add more of this product',
    'products.addedToCart': '{name} added to cart',
    'products.removedFromCart': '{name} removed from cart',
    'products.fetchFailed': 'Failed to fetch products',
    'products.productNotFound': 'Product not found',
    'products.backToProducts': 'Back to products',
    'products.loadFailed': 'Product could not be loaded',
    'products.orderOne': 'Order one item',
    'products.pickupDelivery': 'Pickup and delivery options',
    'products.verifyBeforeOrders': 'Verification is required before placing orders.',
    'products.verifyBeforeBuying': 'Please complete verification before buying.',
    'cart.checkout': 'Checkout',
    'cart.shoppingCart': 'Shopping Cart',
    'cart.emptyTitle': 'Your cart is empty',
    'cart.emptyDesc': 'Add products from the marketplace to start a new order.',
    'cart.each': 'each',
    'cart.remove': 'Remove item',
    'cart.decrease': 'Decrease quantity',
    'cart.increase': 'Increase quantity',
    'cart.fulfillment': 'Fulfillment',
    'cart.pickup': 'Pickup',
    'cart.delivery': 'Delivery',
    'cart.deliveryAddress': 'Delivery Address',
    'cart.deliveryPlaceholder': 'Bole Sub City, Woreda 03, near Medhanialem',
    'cart.subtotal': 'Subtotal',
    'cart.placeOrder': 'Place Order',
    'cart.verifiedRequired': 'Your account must be verified before placing orders',
    'cart.deliveryRequired': 'Delivery address is required for delivery orders',
    'cart.orderSuccess': 'Order placed successfully!',
    'cart.orderFailed': 'Failed to place order',
    'status.pending': 'Pending',
    'status.approved': 'Approved',
    'status.ready': 'Ready for Pickup',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    'stock.out': 'Out',
    'stock.low': 'Low',
    'stock.in': 'In stock',
    'orders.order': 'Order',
    'orders.waitingReview': 'Waiting for store review',
    'orders.approvedScheduled': 'Approved and scheduled',
    'orders.readyPickup': 'Ready for pickup',
    'orders.delivered': 'Delivered to member',
    'orders.cancelled': 'Order cancelled',
    'orders.processing': 'Processing your request',
    'orders.openDetails': 'Open order for product details',
    'dashboard.eyebrow': 'Member home',
    'dashboard.welcome': 'Welcome back, {name}',
    'dashboard.memberFallback': 'member',
    'dashboard.description': 'Browse available products, track your order activity, and keep your verification ready for checkout.',
    'dashboard.browseProducts': 'Browse Products',
    'dashboard.verifyTitle': 'Verification required for checkout',
    'dashboard.verifyWaiting': 'Your verification was submitted and is waiting for admin approval.',
    'dashboard.verifySubmitCopy': 'Submit your kebele ID, coupon ID, and ID image before placing orders.',
    'dashboard.submitVerification': 'Submit Verification',
    'dashboard.totalSpent': 'Total Spent',
    'dashboard.pending': 'Pending',
    'dashboard.unread': 'Unread',
    'dashboard.featured': 'Featured marketplace',
    'dashboard.featuredDesc': 'Quick add popular available products to your pickup order.',
    'dashboard.viewAll': 'View all',
    'dashboard.noProducts': 'No products available',
    'dashboard.noProductsDesc': 'The store catalog is empty right now.',
    'footer.description': 'Products, orders, inventory, and member service.',
    'footer.rights': 'All rights reserved.',
    'manager.catalog': 'Catalog',
    'manager.productManagement': 'Product Management',
    'manager.productManagementDesc': 'Maintain the storefront catalog, pricing, categories, and product availability.',
    'manager.addProduct': 'Add Product',
    'manager.editProduct': 'Edit product',
    'manager.addNewProduct': 'Add new product',
    'manager.productFormDesc': 'Use concise names, clear categories, and accurate stock counts.',
    'manager.nameAm': 'Name (Amharic)',
    'manager.nameOr': 'Name (Afaan Oromo)',
    'manager.descAm': 'Description (Amharic)',
    'manager.descOr': 'Description (Afaan Oromo)',
    'manager.supplier': 'Supplier',
    'manager.noSupplier': 'No supplier',
    'manager.productImage': 'Product Image',
    'manager.imageHint': 'Upload a clear product photo. JPG, PNG, GIF, or WebP up to 2MB.',
    'manager.descriptionLabel': 'Description',
    'manager.saveProduct': 'Save Product',
    'manager.created': 'Product created successfully',
    'manager.updated': 'Product updated successfully',
    'manager.saveFailed': 'Failed to save product',
    'manager.fetchFailed': 'Failed to fetch products',
    'manager.deleteConfirm': 'Are you sure you want to delete this product?',
    'manager.deleted': 'Product deleted successfully',
    'manager.deleteFailed': 'Failed to delete product',
    'manager.noProducts': 'No products yet',
    'manager.noProductsDesc': 'Add your first product to populate the storefront.',
    'admin.eyebrow': 'Administration',
    'admin.dashboard': 'Admin Dashboard',
    'admin.dashboardDesc': 'High-level store performance, member verification, inventory risk, and broadcast controls.',
    'admin.manageUsers': 'Manage Users',
    'admin.manageUsersDesc': 'Verify members and review account details.',
    'admin.viewReports': 'View Reports',
    'admin.viewReportsDesc': 'Analyze inventory, orders, revenue, and member activity.',
    'admin.broadcastNotifications': 'Broadcast Notifications',
    'admin.broadcastNotificationsDesc': 'Send clear operational updates to members.',
    'admin.broadcasts': 'Broadcasts',
    'admin.broadcastTitle': 'Broadcast Notification',
    'admin.broadcastDesc': 'Send concise operational updates to every member dashboard and linked Telegram account.',
    'admin.messageComposer': 'Message composer',
    'admin.messageComposerDesc': 'Keep member-facing messages short, specific, and action oriented.',
    'admin.notificationTitle': 'Notification Title',
    'admin.notificationTitlePlaceholder': 'Fresh teff and oil stock available',
    'admin.message': 'Message',
    'admin.messagePlaceholder': 'Dear members, new stock is ready for pickup at the cooperative store.',
    'admin.sending': 'Sending...',
    'admin.sendAll': 'Send to All Members',
    'admin.fillAll': 'Please fill all fields',
    'admin.sentAll': 'Notification sent to all members!',
    'admin.sendFailed': 'Failed to send notification',
    'users.memberVerification': 'Member Verification',
    'users.management': 'User Management',
    'users.managerDesc': 'Review and verify members assigned to your kebele.',
    'users.adminDesc': 'Search members, verify accounts, and inspect submitted verification documents.',
    'users.searchPlaceholder': 'Search users...',
    'users.noUsers': 'No users found',
    'users.noUsersDesc': 'Try a different search term.',
    'users.member': 'Member',
    'users.role': 'Role',
    'users.managerKebele': 'Manager Kebele',
    'users.verified': 'Verified',
    'users.actions': 'Actions',
    'users.verify': 'Verify',
    'users.unverify': 'Unverify',
    'users.pending': 'Pending',
    'users.phone': 'Phone',
    'users.kebele': 'Kebele',
    'users.notProvided': 'Not provided',
    'users.notAssigned': 'Not assigned',
    'users.fetchFailed': 'Failed to fetch users',
    'users.verifiedOk': 'User verified',
    'users.unverifiedOk': 'User unverified',
    'users.updateFailed': 'Failed to update user',
    'users.accessUpdated': 'Access updated',
    'users.accessFailed': 'Failed to update access',
    'users.walletUpdated': 'Wallet updated',
    'users.walletFailed': 'Failed to adjust wallet',
    'manager.operations': 'Operations',
    'manager.dashboard': 'Manager Dashboard',
    'manager.dashboardDesc': 'Monitor store demand, product availability, and fulfillment queues from one operational cockpit.',
    'manager.manageProducts': 'Manage Products',
    'manager.manageProductsDesc': 'Create, update, and remove catalog products.',
    'manager.processOrders': 'Process Orders',
    'manager.processOrdersDesc': 'Review member orders and update fulfillment status.',
    'manager.inventoryControl': 'Inventory Control',
    'manager.inventoryControlDesc': 'Adjust stock levels and record inventory reasons.',
    'manager.completed': 'Completed',
    'manager.out': 'Out',
    'inventory.title': 'Inventory Management',
    'inventory.desc': 'Adjust stock quantities and capture a reason for every inventory movement.',
    'inventory.currentStock': 'Current Stock',
    'inventory.status': 'Status',
    'inventory.action': 'Action',
    'inventory.reason': 'Reason',
    'inventory.adjust': 'Adjust',
    'inventory.noRecords': 'No inventory records',
    'inventory.noRecordsDesc': 'Products will appear here after they are created.',
    'inventory.updated': 'Inventory updated',
    'inventory.updateFailed': 'Failed to update inventory',
    'reports.analytics': 'Analytics',
    'reports.title': 'Reports',
    'reports.desc': 'Review inventory value, order performance, and member activity with operational tables.',
    'reports.saveCurrent': 'Save current report',
    'reports.inventory': 'Inventory',
    'reports.orders': 'Orders',
    'reports.members': 'Members',
    'reports.revenue': 'Revenue',
    'reports.history': 'Stored report history',
    'reports.historyDesc': 'Saved snapshots remain available after the live report changes.',
    'reports.type': 'Type',
    'reports.generatedBy': 'Generated By',
    'reports.summary': 'Summary',
    'reports.saved': 'Saved',
    'reports.noSaved': 'No saved reports',
    'reports.noSavedDesc': 'Save the current report to build a report history.',
    'reports.stockValue': 'Stock Value',
    'reports.lowStock': 'Low Stock',
    'reports.outOfStock': 'Out of Stock',
    'reports.noProducts': 'No products in report',
    'reports.avgOrder': 'Avg Order',
    'reports.ordersByStatus': 'Orders by status',
    'reports.name': 'Name',
    'reports.totalSpent': 'Total Spent',
    'reports.noMemberActivity': 'No member activity',
    'orders.center': 'Order center',
    'orders.mine': 'My Orders',
    'orders.desc': 'Track request review, approval, pickup readiness, and completed Shemachoch orders.',
    'orders.all': 'All',
    'orders.noFound': 'No orders found',
    'orders.noFoundDesc': 'Orders that match this status will appear here.',
    'messages.communication': 'Communication',
    'messages.title': 'Messages',
    'messages.desc': 'Send and receive internal support messages between members, managers, and admins.',
    'messages.new': 'New message',
    'messages.selectRecipient': 'Select recipient',
    'messages.subject': 'Subject',
    'messages.write': 'Write message...',
    'messages.send': 'Send',
    'messages.inbox': 'Inbox',
    'messages.sent': 'Sent',
    'messages.none': 'No messages yet',
    'messages.noneDesc': 'Your internal conversation history will appear here.',
    'messages.noSubject': 'No subject',
    'messages.to': 'To',
    'messages.from': 'From',
    'messages.user': 'User',
    'messages.loadFailed': 'Failed to load messages',
    'messages.sentOk': 'Message sent',
    'messages.sendFailed': 'Failed to send message',
  },
  am: {
    'common.language': 'ቋንቋ',
    'common.portal': 'ፖርታል',
    'common.close': 'ዝጋ',
    'common.cancel': 'ሰርዝ',
    'common.save': 'አስቀምጥ',
    'common.search': 'ፈልግ',
    'common.details': 'ዝርዝር',
    'common.items': 'እቃዎች',
    'common.product': 'ምርት',
    'common.general': 'አጠቃላይ',
    'common.loading': 'በመጫን ላይ',
    'common.category': 'ምድብ',
    'common.price': 'ዋጋ',
    'common.stock': 'ክምችት',
    'common.value': 'ዋጋ',
    'nav.dashboard': 'ዳሽቦርድ',
    'nav.home': 'መነሻ',
    'nav.products': 'ምርቶች',
    'nav.orders': 'ትዕዛዞች',
    'nav.profile': 'መገለጫ',
    'nav.messages': 'መልዕክቶች',
    'nav.inventory': 'ክምችት',
    'nav.suppliers': 'አቅራቢዎች',
    'nav.users': 'ተጠቃሚዎች',
    'nav.reports': 'ሪፖርቶች',
    'nav.broadcasts': 'ማስታወቂያዎች',
    'nav.supply': 'አቅርቦት',
    'nav.cart': 'ጋሪ',
    'nav.logout': 'ውጣ',
    'nav.tagline': 'የሸማቾች የንግድ ፖርታል',
    'nav.subtagline': 'ትዕዛዞች፣ ክምችት፣ ማረጋገጫ እና ሪፖርቶች በአንድ ቦታ',
    'auth.portalSubtitle': 'የኢ-ኮሜርስ ፖርታል',
    'auth.memberCommerce': 'የአባላት ግብይት',
    'auth.heroTitle': 'ይግዙ፣ ይረጋገጡ እና ትዕዛዞችን በአንድ ስርዓት ያስተዳድሩ።',
    'auth.heroCopy': 'ለአባላት፣ ለማናጀሮች እና ለአስተዳዳሪዎች የተዘጋጀ የስራ ልምድ።',
    'auth.liveInventory': 'ቀጥታ ክምችት',
    'auth.secureCheckout': 'ደህንነቱ የተጠበቀ ክፍያ',
    'auth.adminReports': 'የአስተዳዳሪ ሪፖርቶች',
    'auth.signIn': 'ግባ',
    'auth.accessWorkspace': 'ወደ ሸማቾች የስራ ቦታ ይግቡ።',
    'auth.email': 'ኢሜይል',
    'auth.password': 'የይለፍ ቃል',
    'auth.signingIn': 'በመግባት ላይ...',
    'auth.signInButton': 'ግባ',
    'auth.or': 'ወይም',
    'auth.google': 'በGoogle ቀጥል',
    'auth.noAccount': 'መለያ የለዎትም?',
    'auth.createOne': 'አዲስ ይፍጠሩ',
    'auth.createAccount': 'መለያ ፍጠር',
    'auth.join': 'ሸማቾችን ይቀላቀሉ እና ማረጋገጫዎን ይጀምሩ።',
    'auth.fullName': 'ሙሉ ስም',
    'auth.confirmPassword': 'የይለፍ ቃል ያረጋግጡ',
    'auth.passwordHint': 'ቢያንስ 8 ቁምፊ',
    'auth.confirmPasswordHint': 'የይለፍ ቃሉን ደግመው ያስገቡ',
    'auth.terms': 'የአገልግሎት ውሎችን እና የግላዊነት ፖሊሲን እስማማለሁ።',
    'auth.creating': 'መለያ በመፍጠር ላይ...',
    'auth.alreadyAccount': 'መለያ አለዎት?',
    'auth.sideTitle': 'ለመደብሩ ሙሉ የግብይት እና የስራ ፖርታል።',
    'auth.sideCopy': 'መለያ ይፍጠሩ፣ ማረጋገጫ ያቅርቡ እና ከተፈቀደ በኋላ የአባል ዋጋ ያግኙ።',
    'auth.loginFailed': 'መግባት አልተሳካም',
    'products.marketEyebrow': 'የአባላት ገበያ',
    'products.title': 'የሸማቾች አስፈላጊ ምርቶች',
    'products.description': 'ቀጥታ ክምችት ይፈልጉ፣ የአባል ዋጋዎችን ያነፃፅሩ እና ትዕዛዝዎን ያዘጋጁ።',
    'products.searchPlaceholder': 'ምርቶች፣ ምድቦች እና መግለጫዎችን ፈልግ',
    'products.allCategories': 'ሁሉም ምድቦች',
    'products.all': 'ሁሉም',
    'products.noProducts': 'ምርት አልተገኘም',
    'products.noProductsDesc': 'የፍለጋ ቃልዎን ይቀይሩ ወይም ሌላ ምድብ ይምረጡ።',
    'products.memberPrice': 'የአባል ዋጋ',
    'products.available': 'ይገኛል',
    'products.availableInStock': 'በክምችት ይገኛል',
    'products.addToCart': 'ወደ ጋሪ ጨምር',
    'products.added': 'ታክሏል',
    'products.verifyToBuy': 'ለመግዛት ይረጋገጡ',
    'products.unavailable': 'አይገኝም',
    'products.qualityFallback': 'ጥራት ያለው የሸማቾች ምርት።',
    'products.verificationRequired': 'ማረጋገጫ ያስፈልጋል።',
    'products.outOfStock': 'ይህ ምርት ከክምችት ውጭ ነው',
    'products.maxStock': 'ከዚህ በላይ ማከል አይቻልም',
    'products.addedToCart': '{name} ወደ ጋሪ ታክሏል',
    'products.removedFromCart': '{name} ከጋሪ ተወግዷል',
    'products.fetchFailed': 'ምርቶችን ማምጣት አልተሳካም',
    'products.productNotFound': 'ምርት አልተገኘም',
    'products.backToProducts': 'ወደ ምርቶች ተመለስ',
    'products.loadFailed': 'ምርቱን መጫን አልተቻለም',
    'products.orderOne': 'አንድ እቃ እዘዝ',
    'products.pickupDelivery': 'የመውሰጃ እና የመላኪያ አማራጮች',
    'products.verifyBeforeOrders': 'ትዕዛዝ ከማድረግዎ በፊት ማረጋገጫ ያስፈልጋል።',
    'products.verifyBeforeBuying': 'ከመግዛትዎ በፊት ማረጋገጫዎን ያጠናቁ።',
    'cart.checkout': 'ክፍያ',
    'cart.shoppingCart': 'የግዢ ጋሪ',
    'cart.emptyTitle': 'ጋሪዎ ባዶ ነው',
    'cart.emptyDesc': 'አዲስ ትዕዛዝ ለመጀመር ከገበያው ምርቶችን ያክሉ።',
    'cart.each': 'እያንዳንዱ',
    'cart.remove': 'እቃ አስወግድ',
    'cart.decrease': 'ብዛት ቀንስ',
    'cart.increase': 'ብዛት ጨምር',
    'cart.fulfillment': 'አፈጻጸም',
    'cart.pickup': 'መውሰጃ',
    'cart.delivery': 'መላኪያ',
    'cart.deliveryAddress': 'የመላኪያ አድራሻ',
    'cart.deliveryPlaceholder': 'ቦሌ ክፍለ ከተማ፣ ወረዳ 03፣ መድሃኒዓለም አካባቢ',
    'cart.subtotal': 'ንዑስ ድምር',
    'cart.placeOrder': 'ትዕዛዝ አስገባ',
    'cart.verifiedRequired': 'ትዕዛዝ ለማድረግ መለያዎ መረጋገጥ አለበት',
    'cart.deliveryRequired': 'ለመላኪያ ትዕዛዝ አድራሻ ያስፈልጋል',
    'cart.orderSuccess': 'ትዕዛዝ በተሳካ ሁኔታ ገብቷል!',
    'cart.orderFailed': 'ትዕዛዝ ማስገባት አልተሳካም',
    'status.pending': 'በመጠባበቅ ላይ',
    'status.approved': 'ተፈቅዷል',
    'status.ready': 'ለመውሰጃ ዝግጁ',
    'status.completed': 'ተጠናቋል',
    'status.cancelled': 'ተሰርዟል',
    'stock.out': 'አልቋል',
    'stock.low': 'ዝቅተኛ',
    'stock.in': 'ይገኛል',
    'orders.order': 'ትዕዛዝ',
    'orders.waitingReview': 'የመደብር ግምገማን በመጠበቅ ላይ',
    'orders.approvedScheduled': 'ተፈቅዷል እና ተመድቧል',
    'orders.readyPickup': 'ለመውሰጃ ዝግጁ',
    'orders.delivered': 'ለአባል ተደርሷል',
    'orders.cancelled': 'ትዕዛዝ ተሰርዟል',
    'orders.processing': 'ጥያቄዎ በሂደት ላይ ነው',
    'orders.openDetails': 'የምርት ዝርዝር ለማየት ይክፈቱ',
    'dashboard.eyebrow': 'የአባል መነሻ',
    'dashboard.welcome': 'እንኳን ደህና መጡ፣ {name}',
    'dashboard.memberFallback': 'አባል',
    'dashboard.description': 'ያሉ ምርቶችን ይመልከቱ፣ ትዕዛዞችን ይከታተሉ እና ማረጋገጫዎን ዝግጁ ያድርጉ።',
    'dashboard.browseProducts': 'ምርቶችን ይመልከቱ',
    'dashboard.verifyTitle': 'ለክፍያ ማረጋገጫ ያስፈልጋል',
    'dashboard.verifyWaiting': 'ማረጋገጫዎ ተልኳል እና የአስተዳዳሪ ፈቃድን በመጠበቅ ላይ ነው።',
    'dashboard.verifySubmitCopy': 'ትዕዛዝ ከማድረግዎ በፊት የቀበሌ መታወቂያ፣ ኩፖን መታወቂያ እና የመታወቂያ ፎቶ ያቅርቡ።',
    'dashboard.submitVerification': 'ማረጋገጫ አቅርብ',
    'dashboard.totalSpent': 'ጠቅላላ ወጪ',
    'dashboard.pending': 'በመጠባበቅ',
    'dashboard.unread': 'ያልተነበበ',
    'dashboard.featured': 'የተመረጡ ምርቶች',
    'dashboard.featuredDesc': 'ተወዳጅ ምርቶችን በፍጥነት ወደ ትዕዛዝዎ ያክሉ።',
    'dashboard.viewAll': 'ሁሉንም ይመልከቱ',
    'dashboard.noProducts': 'ምርቶች የሉም',
    'dashboard.noProductsDesc': 'የመደብሩ ካታሎግ አሁን ባዶ ነው።',
    'footer.description': 'ምርቶች፣ ትዕዛዞች፣ ክምችት እና የአባላት አገልግሎት።',
    'footer.rights': 'መብቱ የተጠበቀ ነው።',
    'manager.catalog': 'ካታሎግ',
    'manager.productManagement': 'የምርት አስተዳደር',
    'manager.productManagementDesc': 'የመደብር ካታሎግ፣ ዋጋ፣ ምድብ እና ክምችት ያስተዳድሩ።',
    'manager.addProduct': 'ምርት ጨምር',
    'manager.editProduct': 'ምርት አርትዕ',
    'manager.addNewProduct': 'አዲስ ምርት ጨምር',
    'manager.productFormDesc': 'አጭር ስም፣ ግልጽ ምድብ እና ትክክለኛ ክምችት ይጠቀሙ።',
    'manager.nameAm': 'ስም (አማርኛ)',
    'manager.nameOr': 'ስም (Afaan Oromo)',
    'manager.descAm': 'መግለጫ (አማርኛ)',
    'manager.descOr': 'መግለጫ (Afaan Oromo)',
    'manager.supplier': 'አቅራቢ',
    'manager.noSupplier': 'አቅራቢ የለም',
    'manager.productImage': 'የምርት ፎቶ',
    'manager.imageHint': 'ግልጽ የምርት ፎቶ ይስቀሉ። JPG, PNG, GIF ወይም WebP እስከ 2MB።',
    'manager.descriptionLabel': 'መግለጫ',
    'manager.saveProduct': 'ምርት አስቀምጥ',
    'manager.created': 'ምርት ተፈጥሯል',
    'manager.updated': 'ምርት ተዘምኗል',
    'manager.saveFailed': 'ምርት ማስቀመጥ አልተሳካም',
    'manager.fetchFailed': 'ምርቶችን ማምጣት አልተሳካም',
    'manager.deleteConfirm': 'ይህን ምርት መሰረዝ ይፈልጋሉ?',
    'manager.deleted': 'ምርት ተሰርዟል',
    'manager.deleteFailed': 'ምርት መሰረዝ አልተሳካም',
    'manager.noProducts': 'እስካሁን ምርት የለም',
    'manager.noProductsDesc': 'መደብሩን ለመሙላት የመጀመሪያውን ምርት ያክሉ።',
    'admin.eyebrow': 'አስተዳደር',
    'admin.dashboard': 'የአስተዳዳሪ ዳሽቦርድ',
    'admin.dashboardDesc': 'የመደብር አፈጻጸም፣ የአባላት ማረጋገጫ፣ የክምችት አደጋ እና ማስታወቂያዎች።',
    'admin.manageUsers': 'ተጠቃሚዎችን አስተዳድር',
    'admin.manageUsersDesc': 'አባላትን ያረጋግጡ እና የመለያ ዝርዝሮችን ይመልከቱ።',
    'admin.viewReports': 'ሪፖርቶችን ይመልከቱ',
    'admin.viewReportsDesc': 'ክምችት፣ ትዕዛዞች፣ ገቢ እና የአባላት እንቅስቃሴን ይተንትኑ።',
    'admin.broadcastNotifications': 'ማስታወቂያ ላክ',
    'admin.broadcastNotificationsDesc': 'ለአባላት ግልጽ የስራ ማስታወቂያዎችን ይላኩ።',
    'admin.broadcasts': 'ማስታወቂያዎች',
    'admin.broadcastTitle': 'የማስታወቂያ መላኪያ',
    'admin.broadcastDesc': 'ለአባላት ዳሽቦርድ እና ለTelegram መለያ አጭር ማስታወቂያ ይላኩ።',
    'admin.messageComposer': 'መልዕክት አዘጋጅ',
    'admin.messageComposerDesc': 'ለአባላት አጭር፣ ግልጽ እና ተግባራዊ መልዕክት ይጻፉ።',
    'admin.notificationTitle': 'የማስታወቂያ ርዕስ',
    'admin.notificationTitlePlaceholder': 'አዲስ ጤፍ እና ዘይት ተገኝቷል',
    'admin.message': 'መልዕክት',
    'admin.messagePlaceholder': 'ውድ አባላት፣ አዲስ ክምችት ለመውሰድ ዝግጁ ነው።',
    'admin.sending': 'በመላክ ላይ...',
    'admin.sendAll': 'ለሁሉም አባላት ላክ',
    'admin.fillAll': 'እባክዎ ሁሉንም መስኮች ይሙሉ',
    'admin.sentAll': 'ማስታወቂያ ለሁሉም አባላት ተልኳል!',
    'admin.sendFailed': 'ማስታወቂያ መላክ አልተሳካም',
    'users.memberVerification': 'የአባላት ማረጋገጫ',
    'users.management': 'የተጠቃሚ አስተዳደር',
    'users.managerDesc': 'በቀበሌዎ ያሉ አባላትን ይመልከቱ እና ያረጋግጡ።',
    'users.adminDesc': 'አባላትን ይፈልጉ፣ መለያዎችን ያረጋግጡ እና ሰነዶችን ይመልከቱ።',
    'users.searchPlaceholder': 'ተጠቃሚዎችን ፈልግ...',
    'users.noUsers': 'ተጠቃሚ አልተገኘም',
    'users.noUsersDesc': 'ሌላ የፍለጋ ቃል ይሞክሩ።',
    'users.member': 'አባል',
    'users.role': 'ሚና',
    'users.managerKebele': 'የማናጀር ቀበሌ',
    'users.verified': 'ተረጋግጧል',
    'users.actions': 'ተግባሮች',
    'users.verify': 'አረጋግጥ',
    'users.unverify': 'አለማረጋገጥ',
    'users.pending': 'በመጠባበቅ',
    'users.phone': 'ስልክ',
    'users.kebele': 'ቀበሌ',
    'users.notProvided': 'አልቀረበም',
    'users.notAssigned': 'አልተመደበም',
    'users.fetchFailed': 'ተጠቃሚዎችን ማምጣት አልተሳካም',
    'users.verifiedOk': 'ተጠቃሚ ተረጋግጧል',
    'users.unverifiedOk': 'ተጠቃሚ አልተረጋገጠም',
    'users.updateFailed': 'ተጠቃሚ ማዘመን አልተሳካም',
    'users.accessUpdated': 'መዳረሻ ተዘምኗል',
    'users.accessFailed': 'መዳረሻ ማዘመን አልተሳካም',
    'users.walletUpdated': 'ዋሌት ተዘምኗል',
    'users.walletFailed': 'የዋሌት ለውጥ አልተሳካም',
    'manager.operations': 'ኦፕሬሽን',
    'manager.dashboard': 'የማናጀር ዳሽቦርድ',
    'manager.dashboardDesc': 'የመደብር ፍላጎት፣ የምርት ክምችት እና የትዕዛዝ ሂደቶችን ይከታተሉ።',
    'manager.manageProducts': 'ምርቶችን አስተዳድር',
    'manager.manageProductsDesc': 'የካታሎግ ምርቶችን ይፍጠሩ፣ ያዘምኑ እና ያስወግዱ።',
    'manager.processOrders': 'ትዕዛዞችን አስኬድ',
    'manager.processOrdersDesc': 'የአባላት ትዕዛዞችን ይመልከቱ እና ሁኔታ ያዘምኑ።',
    'manager.inventoryControl': 'የክምችት ቁጥጥር',
    'manager.inventoryControlDesc': 'የክምችት መጠን ያስተካክሉ እና ምክንያት ይመዝግቡ።',
    'manager.completed': 'ተጠናቋል',
    'manager.out': 'አልቋል',
    'inventory.title': 'የክምችት አስተዳደር',
    'inventory.desc': 'የክምችት መጠን ያስተካክሉ እና ለእያንዳንዱ ለውጥ ምክንያት ይመዝግቡ።',
    'inventory.currentStock': 'የአሁን ክምችት',
    'inventory.status': 'ሁኔታ',
    'inventory.action': 'ተግባር',
    'inventory.reason': 'ምክንያት',
    'inventory.adjust': 'አስተካክል',
    'inventory.noRecords': 'የክምችት መዝገብ የለም',
    'inventory.noRecordsDesc': 'ምርቶች ከተፈጠሩ በኋላ እዚህ ይታያሉ።',
    'inventory.updated': 'ክምችት ተዘምኗል',
    'inventory.updateFailed': 'ክምችት ማዘመን አልተሳካም',
    'reports.analytics': 'ትንታኔ',
    'reports.title': 'ሪፖርቶች',
    'reports.desc': 'የክምችት ዋጋ፣ የትዕዛዝ አፈጻጸም እና የአባላት እንቅስቃሴን ይመልከቱ።',
    'reports.saveCurrent': 'የአሁኑን ሪፖርት አስቀምጥ',
    'reports.inventory': 'ክምችት',
    'reports.orders': 'ትዕዛዞች',
    'reports.members': 'አባላት',
    'reports.revenue': 'ገቢ',
    'reports.history': 'የተቀመጡ ሪፖርቶች',
    'reports.historyDesc': 'የተቀመጡ ቅጂዎች ከቀጥታ ሪፖርት በኋላም ይገኛሉ።',
    'reports.type': 'ዓይነት',
    'reports.generatedBy': 'ያመነጨው',
    'reports.summary': 'ማጠቃለያ',
    'reports.saved': 'ተቀምጧል',
    'reports.noSaved': 'የተቀመጠ ሪፖርት የለም',
    'reports.noSavedDesc': 'የሪፖርት ታሪክ ለመጀመር የአሁኑን ሪፖርት ያስቀምጡ።',
    'reports.stockValue': 'የክምችት ዋጋ',
    'reports.lowStock': 'ዝቅተኛ ክምችት',
    'reports.outOfStock': 'ከክምችት ውጭ',
    'reports.noProducts': 'በሪፖርት ውስጥ ምርት የለም',
    'reports.avgOrder': 'አማካይ ትዕዛዝ',
    'reports.ordersByStatus': 'ትዕዛዞች በሁኔታ',
    'reports.name': 'ስም',
    'reports.totalSpent': 'ጠቅላላ ወጪ',
    'reports.noMemberActivity': 'የአባላት እንቅስቃሴ የለም',
    'orders.center': 'የትዕዛዝ ማዕከል',
    'orders.mine': 'የእኔ ትዕዛዞች',
    'orders.desc': 'ግምገማ፣ ፈቃድ፣ ዝግጁነት እና የተጠናቀቁ ትዕዛዞችን ይከታተሉ።',
    'orders.all': 'ሁሉም',
    'orders.noFound': 'ትዕዛዝ አልተገኘም',
    'orders.noFoundDesc': 'ከዚህ ሁኔታ ጋር የሚዛመዱ ትዕዛዞች እዚህ ይታያሉ።',
    'messages.communication': 'ግንኙነት',
    'messages.title': 'መልዕክቶች',
    'messages.desc': 'በአባላት፣ ማናጀሮች እና አስተዳዳሪዎች መካከል የድጋፍ መልዕክቶችን ይላኩ እና ይቀበሉ።',
    'messages.new': 'አዲስ መልዕክት',
    'messages.selectRecipient': 'ተቀባይ ይምረጡ',
    'messages.subject': 'ርዕስ',
    'messages.write': 'መልዕክት ይጻፉ...',
    'messages.send': 'ላክ',
    'messages.inbox': 'ገቢ',
    'messages.sent': 'የተላኩ',
    'messages.none': 'እስካሁን መልዕክት የለም',
    'messages.noneDesc': 'የውስጥ መልዕክት ታሪክዎ እዚህ ይታያል።',
    'messages.noSubject': 'ርዕስ የለም',
    'messages.to': 'ወደ',
    'messages.from': 'ከ',
    'messages.user': 'ተጠቃሚ',
    'messages.loadFailed': 'መልዕክቶችን ማምጣት አልተሳካም',
    'messages.sentOk': 'መልዕክት ተልኳል',
    'messages.sendFailed': 'መልዕክት መላክ አልተሳካም',
  },
  or: {
    'common.language': 'Afaan',
    'common.portal': 'Poortaalii',
    'common.close': 'Cufi',
    'common.cancel': 'Dhiisi',
    'common.save': 'Ol kaa’i',
    'common.search': 'Barbaadi',
    'common.details': 'Bal’ina',
    'common.items': 'meeshaalee',
    'common.product': 'Oomisha',
    'common.general': 'Waliigala',
    'common.loading': 'Fe’amaa jira',
    'common.category': 'Gosa',
    'common.price': 'Gatii',
    'common.stock': 'Kuusaa',
    'common.value': 'Gatii waliigalaa',
    'nav.dashboard': 'Daashboordii',
    'nav.home': 'Mana',
    'nav.products': 'Oomishaalee',
    'nav.orders': 'Ajajawwan',
    'nav.profile': 'Profaayilii',
    'nav.messages': 'Ergaawwan',
    'nav.inventory': 'Kuusaa',
    'nav.suppliers': 'Dhiyeessitoota',
    'nav.users': 'Fayyadamtoota',
    'nav.reports': 'Gabaasota',
    'nav.broadcasts': 'Beeksisawwan',
    'nav.supply': 'Dhiyeessii',
    'nav.cart': 'Gaarii',
    'nav.logout': 'Ba’i',
    'nav.tagline': 'Poortaalii daldalaa Shemachoch',
    'nav.subtagline': 'Ajaja, kuusaa, mirkaneessa, fi gabaasa iddoo tokkootti',
    'auth.portalSubtitle': 'Poortaalii e-commerce',
    'auth.memberCommerce': 'Daldala miseensotaa',
    'auth.heroTitle': 'Biti, mirkaneessi, ajajawwanis bakka tokkootti bulchi.',
    'auth.heroCopy': 'Muuxannoo hojii miseensota, maanejeroota, fi bulchitootaaf qophaa’e.',
    'auth.liveInventory': 'Kuusaa yeroo ammaa',
    'auth.secureCheckout': 'Kaffaltii nageenya qabu',
    'auth.adminReports': 'Gabaasa bulchaa',
    'auth.signIn': 'Seeni',
    'auth.accessWorkspace': 'Iddoo hojii Shemachoch seeni.',
    'auth.email': 'Imeelii',
    'auth.password': 'Jecha icciitii',
    'auth.signingIn': 'Seenaa jira...',
    'auth.signInButton': 'Seeni',
    'auth.or': 'YKN',
    'auth.google': 'Google’n itti fufi',
    'auth.noAccount': 'Akkaawuntii hin qabduu?',
    'auth.createOne': 'Tokko uumi',
    'auth.createAccount': 'Akkaawuntii uumi',
    'auth.join': 'Shemachochtti makami, mirkaneessa kee jalqabi.',
    'auth.fullName': 'Maqaa guutuu',
    'auth.confirmPassword': 'Jecha icciitii mirkaneessi',
    'auth.passwordHint': 'Yoo xiqqaate arfii 8',
    'auth.confirmPasswordHint': 'Jecha icciitii irra deebi’i',
    'auth.terms': 'Haala tajaajilaa fi imaammata iccitii irratti walii galeera.',
    'auth.creating': 'Akkaawuntii uumamaa jira...',
    'auth.alreadyAccount': 'Akkaawuntii qabdaa?',
    'auth.sideTitle': 'Poortaalii bittaa fi hojii suuqii guutuu.',
    'auth.sideCopy': 'Akkaawuntii uumi, mirkaneessa dhiyeessi, erga ragga’e gatii miseensaa argadhu.',
    'auth.loginFailed': 'Seenuun hin milkoofne',
    'products.marketEyebrow': 'Gabaa miseensotaa',
    'products.title': 'Meeshaalee barbaachisoo Shemachoch',
    'products.description': 'Kuusaa yeroo ammaa barbaadi, gatii miseensaa madaali, ajaja fudhannaa qopheessi.',
    'products.searchPlaceholder': 'Oomisha, gosoota, fi ibsa barbaadi',
    'products.allCategories': 'Gosoota hunda',
    'products.all': 'Hunda',
    'products.noProducts': 'Oomishni hin argamne',
    'products.noProductsDesc': 'Jechoota barbaacha jijjiiri ykn gosa biraa filadhu.',
    'products.memberPrice': 'Gatii miseensaa',
    'products.available': 'jira',
    'products.availableInStock': 'kuusaa keessa jira',
    'products.addToCart': 'Gaariitti dabali',
    'products.added': 'Dabalame',
    'products.verifyToBuy': 'Bitachuuf mirkaneessi',
    'products.unavailable': 'Hin jiru',
    'products.qualityFallback': 'Oomisha Shemachoch qulqullina qabu.',
    'products.verificationRequired': 'Mirkaneessi barbaachisa.',
    'products.outOfStock': 'Oomishni kun kuusaa keessaa dhumeera',
    'products.maxStock': 'Oomisha kana caalaa dabaluun hin danda’amu',
    'products.addedToCart': '{name} gaariitti dabalame',
    'products.removedFromCart': '{name} gaarii keessaa baafame',
    'products.fetchFailed': 'Oomishaalee fiduun hin milkoofne',
    'products.productNotFound': 'Oomishni hin argamne',
    'products.backToProducts': 'Gara oomishaaleetti deebi’i',
    'products.loadFailed': 'Oomisha fe’uun hin danda’amne',
    'products.orderOne': 'Meeshaa tokko ajaji',
    'products.pickupDelivery': 'Filannoo fudhannaa fi geejjibaa',
    'products.verifyBeforeOrders': 'Ajaja gochuun dura mirkaneessi barbaachisa.',
    'products.verifyBeforeBuying': 'Bitachuu dura mirkaneessa kee xumuri.',
    'cart.checkout': 'Kaffaltii',
    'cart.shoppingCart': 'Gaarii bittaa',
    'cart.emptyTitle': 'Gaariin kee duwwaa dha',
    'cart.emptyDesc': 'Ajaja haaraa jalqabuuf oomishaalee gabaa irraa dabali.',
    'cart.each': 'tokko tokkoon',
    'cart.remove': 'Meeshaa haqi',
    'cart.decrease': 'Baay’ina hir’isi',
    'cart.increase': 'Baay’ina dabali',
    'cart.fulfillment': 'Raawwii',
    'cart.pickup': 'Fudhannaa',
    'cart.delivery': 'Geessuu',
    'cart.deliveryAddress': 'Teessoo geessuu',
    'cart.deliveryPlaceholder': 'Bole Sub City, Woreda 03, Medhanialem bira',
    'cart.subtotal': 'Ida’ama xiqqaa',
    'cart.placeOrder': 'Ajaja galchi',
    'cart.verifiedRequired': 'Ajaja gochuuf akkaawuntiin kee mirkanaa’uu qaba',
    'cart.deliveryRequired': 'Ajaja geessuudhaaf teessoon barbaachisa',
    'cart.orderSuccess': 'Ajajni milkaa’ee galmaa’e!',
    'cart.orderFailed': 'Ajaja galchuun hin milkoofne',
    'status.pending': 'Eegamaa jira',
    'status.approved': 'Ragga’eera',
    'status.ready': 'Fudhachuuf qophaa’eera',
    'status.completed': 'Xumurameera',
    'status.cancelled': 'Haqameera',
    'stock.out': 'Dhumeera',
    'stock.low': 'Xiqqaa',
    'stock.in': 'Jira',
    'orders.order': 'Ajaja',
    'orders.waitingReview': 'Suuqiin ilaalaa jira',
    'orders.approvedScheduled': 'Ragga’ee saganteeffameera',
    'orders.readyPickup': 'Fudhachuuf qophaa’eera',
    'orders.delivered': 'Miseensatti geessameera',
    'orders.cancelled': 'Ajajni haqameera',
    'orders.processing': 'Gaaffiin kee hojjetamaa jira',
    'orders.openDetails': 'Bal’ina oomishaa arguuf bani',
    'dashboard.eyebrow': 'Mana miseensaa',
    'dashboard.welcome': 'Baga nagaan deebite, {name}',
    'dashboard.memberFallback': 'miseensa',
    'dashboard.description': 'Oomisha jiru ilaali, sochii ajajaa hordofi, mirkaneessa kees kaffaltiif qopheessi.',
    'dashboard.browseProducts': 'Oomishaalee ilaali',
    'dashboard.verifyTitle': 'Kaffaltiif mirkaneessi barbaachisa',
    'dashboard.verifyWaiting': 'Mirkaneessi kee ergamee raggaasa bulchaa eegaa jira.',
    'dashboard.verifySubmitCopy': 'Ajaja dura Kebele ID, coupon ID, fi suuraa eenyummaa galchi.',
    'dashboard.submitVerification': 'Mirkaneessa galchi',
    'dashboard.totalSpent': 'Baasi waliigalaa',
    'dashboard.pending': 'Eegamaa',
    'dashboard.unread': 'Hin dubbifamne',
    'dashboard.featured': 'Gabaa filatamaa',
    'dashboard.featuredDesc': 'Oomishaalee beekamoo daftee ajaja fudhannaatti dabali.',
    'dashboard.viewAll': 'Hundaa ilaali',
    'dashboard.noProducts': 'Oomishni hin jiru',
    'dashboard.noProductsDesc': 'Kaataalogiin suuqii yeroo ammaa duwwaa dha.',
    'footer.description': 'Oomisha, ajaja, kuusaa, fi tajaajila miseensotaa.',
    'footer.rights': 'Mirgi hundi eegameera.',
    'manager.catalog': 'Kaataalogii',
    'manager.productManagement': 'Bulchiinsa Oomishaa',
    'manager.productManagementDesc': 'Kaataalogii, gatii, gosoota, fi argama oomishaa bulchi.',
    'manager.addProduct': 'Oomisha dabali',
    'manager.editProduct': 'Oomisha gulaali',
    'manager.addNewProduct': 'Oomisha haaraa dabali',
    'manager.productFormDesc': 'Maqaa gabaabaa, gosa ifa, fi lakkoofsa kuusaa sirrii fayyadami.',
    'manager.nameAm': 'Maqaa (Amharic)',
    'manager.nameOr': 'Maqaa (Afaan Oromo)',
    'manager.descAm': 'Ibsa (Amharic)',
    'manager.descOr': 'Ibsa (Afaan Oromo)',
    'manager.supplier': 'Dhiyeessaa',
    'manager.noSupplier': 'Dhiyeessaa hin qabu',
    'manager.productImage': 'Suuraa oomishaa',
    'manager.imageHint': 'Suuraa oomishaa ifa ta’e olkaa’i. JPG, PNG, GIF, yookaan WebP hanga 2MB.',
    'manager.descriptionLabel': 'Ibsa',
    'manager.saveProduct': 'Oomisha ol kaa’i',
    'manager.created': 'Oomishni milkaa’ee uumame',
    'manager.updated': 'Oomishni milkaa’ee haaromfame',
    'manager.saveFailed': 'Oomisha olkaa’uun hin milkoofne',
    'manager.fetchFailed': 'Oomishaalee fiduun hin milkoofne',
    'manager.deleteConfirm': 'Oomisha kana haqiuu barbaaddaa?',
    'manager.deleted': 'Oomishni haqameera',
    'manager.deleteFailed': 'Oomisha haquun hin milkoofne',
    'manager.noProducts': 'Oomishni amma hin jiru',
    'manager.noProductsDesc': 'Suuqii guutuuf oomisha jalqabaa dabali.',
    'admin.eyebrow': 'Bulchiinsa',
    'admin.dashboard': 'Daashboordii Bulchaa',
    'admin.dashboardDesc': 'Raawwii suuqii, mirkaneessa miseensotaa, balaa kuusaa, fi beeksisawwan.',
    'admin.manageUsers': 'Fayyadamtoota Bulchi',
    'admin.manageUsersDesc': 'Miseensota mirkaneessi, bal’ina akkaawuntii ilaali.',
    'admin.viewReports': 'Gabaasota Ilaali',
    'admin.viewReportsDesc': 'Kuusaa, ajaja, galii, fi sochii miseensotaa xiinxali.',
    'admin.broadcastNotifications': 'Beeksisa Ergii',
    'admin.broadcastNotificationsDesc': 'Miseensotaaf odeeffannoo hojii ifa ta’e ergi.',
    'admin.broadcasts': 'Beeksisawwan',
    'admin.broadcastTitle': 'Beeksisa Waliigalaa',
    'admin.broadcastDesc': 'Daashboordii miseensotaa fi Telegram walqabateef beeksisa gabaabaa ergi.',
    'admin.messageComposer': 'Qopheessaa ergaa',
    'admin.messageComposerDesc': 'Ergaa miseensotaaf gabaabaa, ifa, fi hojii irratti xiyyeeffate barreessi.',
    'admin.notificationTitle': 'Mata duree beeksisaa',
    'admin.notificationTitlePlaceholder': 'Teffii fi zayitiin haaraan jira',
    'admin.message': 'Ergaa',
    'admin.messagePlaceholder': 'Miseensota kabajamoo, kuusaan haaraan fudhannaaf qophaa’eera.',
    'admin.sending': 'Ergamaa jira...',
    'admin.sendAll': 'Miseensota Hundaaf Ergi',
    'admin.fillAll': 'Mee dirree hunda guuti',
    'admin.sentAll': 'Beeksisni miseensota hundaaf ergameera!',
    'admin.sendFailed': 'Beeksisa erguun hin milkoofne',
    'users.memberVerification': 'Mirkaneessa Miseensotaa',
    'users.management': 'Bulchiinsa Fayyadamtootaa',
    'users.managerDesc': 'Miseensota kebelee keetti ramadaman ilaali fi mirkaneessi.',
    'users.adminDesc': 'Miseensota barbaadi, akkaawuntii mirkaneessi, sanadoota ilaali.',
    'users.searchPlaceholder': 'Fayyadamtoota barbaadi...',
    'users.noUsers': 'Fayyadamaan hin argamne',
    'users.noUsersDesc': 'Jechoota barbaacha biraa yaali.',
    'users.member': 'Miseensa',
    'users.role': 'Gahee',
    'users.managerKebele': 'Kebelee maanejerii',
    'users.verified': 'Mirkanaa’e',
    'users.actions': 'Tarkaanfii',
    'users.verify': 'Mirkaneessi',
    'users.unverify': 'Mirkaneessa kaasi',
    'users.pending': 'Eegamaa',
    'users.phone': 'Bilbila',
    'users.kebele': 'Kebelee',
    'users.notProvided': 'Hin kennamne',
    'users.notAssigned': 'Hin ramadamne',
    'users.fetchFailed': 'Fayyadamtoota fiduun hin milkoofne',
    'users.verifiedOk': 'Fayyadamaan mirkanaa’eera',
    'users.unverifiedOk': 'Mirkaneessi fayyadamaa kaafameera',
    'users.updateFailed': 'Fayyadamaa haaromsuun hin milkoofne',
    'users.accessUpdated': 'Eeyyamni haaromfameera',
    'users.accessFailed': 'Eeyyama haaromsuun hin milkoofne',
    'users.walletUpdated': 'Waaleetiin haaromfameera',
    'users.walletFailed': 'Waaleetii sirreessuun hin milkoofne',
    'manager.operations': 'Hojiiwwan',
    'manager.dashboard': 'Daashboordii Maanejerii',
    'manager.dashboardDesc': 'Fedhii suuqii, argama oomishaa, fi tarree raawwii hordofi.',
    'manager.manageProducts': 'Oomishaalee Bulchi',
    'manager.manageProductsDesc': 'Oomishaalee kaataalogii uumi, haaromsi, haqi.',
    'manager.processOrders': 'Ajajawwan Hojjedhu',
    'manager.processOrdersDesc': 'Ajajawwan miseensotaa ilaali, haala raawwii haaromsi.',
    'manager.inventoryControl': 'To’annoo Kuusaa',
    'manager.inventoryControlDesc': 'Sadarkaa kuusaa sirreessi, sababoota galmeessi.',
    'manager.completed': 'Xumurame',
    'manager.out': 'Dhume',
    'inventory.title': 'Bulchiinsa Kuusaa',
    'inventory.desc': 'Baay’ina kuusaa sirreessi, sababaa sochii kuusaa galmeessi.',
    'inventory.currentStock': 'Kuusaa amma',
    'inventory.status': 'Haala',
    'inventory.action': 'Tarkaanfii',
    'inventory.reason': 'Sababa',
    'inventory.adjust': 'Sirreessi',
    'inventory.noRecords': 'Galmeen kuusaa hin jiru',
    'inventory.noRecordsDesc': 'Oomishaaleen erga uumaman booda asitti mul’atu.',
    'inventory.updated': 'Kuusaan haaromfame',
    'inventory.updateFailed': 'Kuusaa haaromsuun hin milkoofne',
    'reports.analytics': 'Xiinxala',
    'reports.title': 'Gabaasota',
    'reports.desc': 'Gatii kuusaa, raawwii ajajaa, fi sochii miseensotaa ilaali.',
    'reports.saveCurrent': 'Gabaasa ammaa ol kaa’i',
    'reports.inventory': 'Kuusaa',
    'reports.orders': 'Ajajawwan',
    'reports.members': 'Miseensota',
    'reports.revenue': 'Galii',
    'reports.history': 'Seenaa gabaasa ol kaa’ame',
    'reports.historyDesc': 'Gabaasni ol kaa’ame erga gabaasni yeroo ammaa jijjiiramee booda ni jiraata.',
    'reports.type': 'Gosa',
    'reports.generatedBy': 'Kan uume',
    'reports.summary': 'Cuunfaa',
    'reports.saved': 'Ol kaa’ame',
    'reports.noSaved': 'Gabaasni ol kaa’ame hin jiru',
    'reports.noSavedDesc': 'Seenaa gabaasaa jalqabuuf gabaasa ammaa ol kaa’i.',
    'reports.stockValue': 'Gatii kuusaa',
    'reports.lowStock': 'Kuusaa xiqqaa',
    'reports.outOfStock': 'Kuusaa keessaa dhume',
    'reports.noProducts': 'Gabaasa keessa oomishni hin jiru',
    'reports.avgOrder': 'Ajaja giddu galeessaa',
    'reports.ordersByStatus': 'Ajajawwan haalaan',
    'reports.name': 'Maqaa',
    'reports.totalSpent': 'Baasi waliigalaa',
    'reports.noMemberActivity': 'Sochiin miseensaa hin jiru',
    'orders.center': 'Giddugala ajajaa',
    'orders.mine': 'Ajajawwan koo',
    'orders.desc': 'Ilaalcha, raggaasa, qophaa’uu fudhannaa, fi ajajawwan xumuraman hordofi.',
    'orders.all': 'Hunda',
    'orders.noFound': 'Ajajni hin argamne',
    'orders.noFoundDesc': 'Ajajawwan haala kanaan walsiman asitti mul’atu.',
    'messages.communication': 'Quunnamtii',
    'messages.title': 'Ergaawwan',
    'messages.desc': 'Ergaawwan deeggarsa keessaa miseensota, maanejeroota, fi bulchitoota gidduutti ergi fi fudhadhu.',
    'messages.new': 'Ergaa haaraa',
    'messages.selectRecipient': 'Fudhataa fili',
    'messages.subject': 'Mata duree',
    'messages.write': 'Ergaa barreessi...',
    'messages.send': 'Ergi',
    'messages.inbox': 'Sanduuqa seensaa',
    'messages.sent': 'Ergame',
    'messages.none': 'Ergaan amma hin jiru',
    'messages.noneDesc': 'Seenaa ergaa keessoo kee asitti argita.',
    'messages.noSubject': 'Mata dureen hin jiru',
    'messages.to': 'Gara',
    'messages.from': 'Irraa',
    'messages.user': 'Fayyadamaa',
    'messages.loadFailed': 'Ergaawwan fe’uun hin milkoofne',
    'messages.sentOk': 'Ergaan ergameera',
    'messages.sendFailed': 'Ergaa erguun hin milkoofne',
  },
}

const categoryTranslations = {
  am: {
    Grains: 'እህሎች',
    Legumes: 'ጥራጥሬዎች',
    Oils: 'ዘይቶች',
    Sweeteners: 'ጣፋጮች',
    Condiments: 'ቅመሞች',
    Beverages: 'መጠጦች',
    Dairy: 'የወተት ምርቶች',
    Household: 'የቤት እቃዎች',
    Stationery: 'የጽሕፈት መሳሪያዎች',
  },
  or: {
    Grains: 'Midhaan',
    Legumes: 'Midhaan dheedhii',
    Oils: 'Zayitii',
    Sweeteners: 'Mi’eessituu',
    Condiments: 'Mi’eessituu nyaataa',
    Beverages: 'Dhugaatii',
    Dairy: 'Oomisha aannanii',
    Household: 'Meeshaa mana keessaa',
    Stationery: 'Meeshaa barreessuu',
  },
}

function interpolate(value, replacements = {}) {
  return Object.entries(replacements).reduce((text, [key, replacement]) => text.replaceAll(`{${key}}`, replacement), value)
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    const stored = localStorage.getItem(STORAGE_KEY)
    return languages.some(item => item.code === stored) ? stored : 'en'
  })

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language)
    document.documentElement.lang = language
  }, [language])

  const value = useMemo(() => {
    const setLanguage = (code) => {
      if (languages.some(item => item.code === code)) setLanguageState(code)
    }

    const t = (key, replacements) => {
      const raw = dictionary[language]?.[key] ?? dictionary.en[key] ?? key
      return interpolate(raw, replacements)
    }

    const productName = (product) => {
      if (!product) return ''
      if (language === 'am') return product.name_am || product.name || ''
      if (language === 'or') return product.name_or || product.name || ''
      return product.name || ''
    }

    const productDescription = (product) => {
      if (!product) return ''
      if (language === 'am') return product.description_am || product.description || ''
      if (language === 'or') return product.description_or || product.description || ''
      return product.description || ''
    }

    const categoryLabel = (category) => categoryTranslations[language]?.[category] || category || t('common.general')
    const statusLabel = (status) => {
      const key = `status.${status}`
      const label = t(key)
      return label === key ? status : label
    }

    return { language, setLanguage, languages, t, productName, productDescription, categoryLabel, statusLabel }
  }, [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider')
  return context
}
