import { useEffect, useState } from 'react'
import { Boxes, Save, ShoppingCart, Users } from 'lucide-react'
import AppLayout from '../../components/AppLayout'
import LoadingSpinner from '../../components/LoadingSpinner'
import { Button, DataTable, EmptyState, PageHeader, SectionCard, StatCard } from '../../components/ui'
import { formatBirr } from '../../utils/currency'
import api from '../../services/api'

const tabs = [
  { key: 'inventory', label: 'Inventory', icon: Boxes },
  { key: 'orders', label: 'Orders', icon: ShoppingCart },
  { key: 'members', label: 'Members', icon: Users },
]

export default function Reports() {
  const [activeTab, setActiveTab] = useState('inventory')
  const [reportData, setReportData] = useState(null)
  const [storedReports, setStoredReports] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchReport()
    fetchStoredReports()
  }, [activeTab])

  const fetchReport = async () => {
    setLoading(true)
    try {
      const response = await api.get(`/reports/${activeTab}`)
      setReportData(response.data)
    } catch (err) {
      console.error('Failed to fetch report:', err)
    } finally {
      setLoading(false)
    }
  }

  const fetchStoredReports = async () => {
    try {
      const response = await api.get('/reports/stored')
      setStoredReports(response.data.data || [])
    } catch (err) {
      console.error('Failed to fetch report history:', err)
    }
  }

  const saveReport = async () => {
    try {
      await api.post('/reports/stored', { type: activeTab })
      fetchStoredReports()
    } catch (err) {
      console.error('Failed to save report:', err)
    }
  }

  return (
    <AppLayout>
      <PageHeader
        eyebrow="Analytics"
        title="Reports"
        description="Review inventory value, order performance, and member activity with operational tables."
        actions={<Button onClick={saveReport}><Save size={16} /> Save current report</Button>}
      />

      <div className="mb-4 flex gap-2 overflow-x-auto rounded-lg border border-slate-200 bg-white p-2 shadow-sm sm:mb-6">
        {tabs.map(tab => {
          const Icon = tab.icon
          return (
            <button
              key={tab.key}
              onClick={() => setActiveTab(tab.key)}
              className={`flex items-center gap-2 whitespace-nowrap rounded-md px-4 py-2 text-sm font-bold transition ${
                activeTab === tab.key ? 'bg-slate-900 text-white' : 'text-slate-600 hover:bg-slate-100'
              }`}
            >
              <Icon size={16} />
              {tab.label}
            </button>
          )
        })}
      </div>

      {loading ? <LoadingSpinner /> : (
        <>
          {activeTab === 'inventory' && <InventoryReport data={reportData} />}
          {activeTab === 'orders' && <OrdersReport data={reportData} />}
          {activeTab === 'members' && <MembersReport data={reportData} />}
          <ReportHistory reports={storedReports} />
        </>
      )}
    </AppLayout>
  )
}

function ReportHistory({ reports }) {
  const columns = [
    { key: 'type', header: 'Type', render: r => <span className="font-black capitalize text-slate-950">{r.type}</span> },
    { key: 'generator', header: 'Generated By', render: r => r.generator?.name || 'Admin' },
    { key: 'summary', header: 'Summary', render: r => Object.entries(r.summary || {}).map(([key, value]) => `${key.replace('_', ' ')}: ${typeof value === 'number' ? value.toLocaleString() : value}`).join(' • ') },
    { key: 'created_at', header: 'Saved', render: r => new Date(r.created_at).toLocaleString() },
  ]

  return (
    <div className="mt-6">
      <SectionCard title="Stored report history" description="Saved snapshots remain available after the live report changes.">
        <DataTable columns={columns} rows={reports || []} empty={<EmptyState title="No saved reports" description="Save the current report to build a report history." />} />
      </SectionCard>
    </div>
  )
}

function InventoryReport({ data }) {
  if (!data) return null
  const columns = [
    { key: 'name', header: 'Product', render: p => <p className="font-bold text-slate-950">{p.name}</p> },
    { key: 'category', header: 'Category' },
    { key: 'price', header: 'Price', cellClassName: 'text-right', render: p => formatBirr(p.price) },
    { key: 'quantity', header: 'Stock', cellClassName: 'text-right font-bold' },
    { key: 'value', header: 'Value', cellClassName: 'text-right font-black text-slate-950', render: p => formatBirr(Number(p.price) * Number(p.quantity)) },
  ]
  return (
    <div className="space-y-6">
      <div className="grid grid-cols-2 gap-3 sm:gap-4 md:grid-cols-4">
        <StatCard title="Products" value={data.total_products} icon={Boxes} tone="sky" />
        <StatCard title="Stock Value" value={formatBirr(data.total_stock_value)} icon={Boxes} tone="emerald" />
        <StatCard title="Low Stock" value={data.low_stock_count} icon={Boxes} tone="amber" />
        <StatCard title="Out of Stock" value={data.out_of_stock_count} icon={Boxes} tone="rose" />
      </div>
      <DataTable columns={columns} rows={data.products || []} empty={<EmptyState title="No products in report" />} />
    </div>
  )
}

function OrdersReport({ data }) {
  if (!data) return null
  return (
    <div className="space-y-6">
      <div className="grid grid-cols-2 gap-3 sm:gap-4 md:grid-cols-3">
        <StatCard title="Orders" value={data.total_orders} icon={ShoppingCart} tone="sky" />
        <StatCard title="Revenue" value={formatBirr(data.total_revenue)} icon={ShoppingCart} tone="emerald" />
        <StatCard title="Avg Order" value={formatBirr(data.avg_order_value)} icon={ShoppingCart} tone="amber" />
      </div>
      <SectionCard title="Orders by status">
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
          {Object.entries(data.status_breakdown || {}).map(([status, count]) => (
            <div key={status} className="rounded-lg border border-slate-200 bg-slate-50 p-4">
              <p className="text-sm font-bold capitalize text-slate-600">{status}</p>
              <p className="mt-2 text-2xl font-black text-slate-950">{count}</p>
            </div>
          ))}
        </div>
      </SectionCard>
    </div>
  )
}

function MembersReport({ data }) {
  if (!data) return null
  const columns = [
    { key: 'name', header: 'Name', render: m => <p className="font-bold text-slate-950">{m.name}</p> },
    { key: 'phone', header: 'Phone' },
    { key: 'orders_count', header: 'Orders', cellClassName: 'text-center font-bold' },
    { key: 'total_orders_value', header: 'Total Spent', cellClassName: 'text-right font-black text-slate-950', render: m => formatBirr(m.total_orders_value) },
    { key: 'is_verified', header: 'Status', cellClassName: 'text-center', render: m => m.is_verified ? 'Verified' : 'Pending' },
  ]
  return (
    <div className="space-y-6">
      <div className="grid grid-cols-2 gap-3 sm:gap-4 md:grid-cols-3">
        <StatCard title="Members" value={data.total_members} icon={Users} tone="sky" />
        <StatCard title="Verified" value={data.verified_members} icon={Users} tone="emerald" />
        <StatCard title="Pending" value={data.unverified_members} icon={Users} tone="amber" />
      </div>
      <DataTable columns={columns} rows={(data.member_activity || []).slice(0, 10)} empty={<EmptyState title="No member activity" />} />
    </div>
  )
}
